Imports System.Collections.ObjectModel
''' <summary>
''' Represents the result of a query, command, insert, update, delete, or stored procedure execution.
''' </summary>
Public NotInheritable Class MySqlResponse
    Private Shared ReadOnly EmptyRows As IReadOnlyList(Of IReadOnlyDictionary(Of String, Object)) = Array.Empty(Of IReadOnlyDictionary(Of String, Object))()
    Private ReadOnly _OutputParameters As IReadOnlyDictionary(Of String, Object)
    Friend Sub New(Optional ResultSets As IEnumerable(Of MySqlResultSet) = Nothing, Optional AffectedRows As Long = 0, Optional LastInsertedId As Long? = Nothing, Optional OutputParameters As IDictionary(Of String, Object) = Nothing, Optional ReturnValue As Object = Nothing)
        Me.ResultSets = New ReadOnlyCollection(Of MySqlResultSet)(If(ResultSets, Enumerable.Empty(Of MySqlResultSet)()).ToList())
        Dim OutputValues As IDictionary(Of String, Object) = If(OutputParameters, New Dictionary(Of String, Object)(StringComparer.OrdinalIgnoreCase))
        _OutputParameters = New ReadOnlyDictionary(Of String, Object)(New Dictionary(Of String, Object)(OutputValues, StringComparer.OrdinalIgnoreCase))
        Me.AffectedRows = AffectedRows
        Me.LastInsertedId = LastInsertedId
        Me.ReturnValue = ReturnValue
    End Sub
    ''' <summary>
    ''' Gets all result sets returned by the operation.
    ''' </summary>
    Public ReadOnly Property ResultSets As IReadOnlyList(Of MySqlResultSet)
    ''' <summary>
    ''' Gets the rows from the first result set, or an empty collection when no data was returned.
    ''' </summary>
    Public ReadOnly Property Data As IReadOnlyList(Of IReadOnlyDictionary(Of String, Object))
        Get
            If ResultSets.Count = 0 Then Return EmptyRows
            Return ResultSets(0).Rows
        End Get
    End Property
    ''' <summary>
    ''' Gets whether at least one returned result set contains a row.
    ''' </summary>
    Public ReadOnly Property HasData As Boolean
        Get
            Return ResultSets.Any(Function(resultSet) resultSet.Rows.Count > 0)
        End Get
    End Property
    ''' <summary>
    ''' Gets the number of rows affected by the command.
    ''' </summary>
    Public ReadOnly Property AffectedRows As Long
    ''' <summary>
    ''' Gets the identifier generated by the last INSERT command, or <see langword="Nothing"/> when the operation was not an insert or no identifier was generated.
    ''' </summary>
    Public ReadOnly Property LastInsertedId As Long?
    ''' <summary>
    ''' Gets stored procedure output and input/output parameter values by normalized parameter name.
    ''' </summary>
    Public ReadOnly Property OutputParameters As IReadOnlyDictionary(Of String, Object)
        Get
            Return _OutputParameters
        End Get
    End Property
    ''' <summary>
    ''' Gets a stored procedure return value, when one was declared.
    ''' </summary>
    Public ReadOnly Property ReturnValue As Object
End Class
