Imports System.Runtime.InteropServices
''' <summary>
''' Provides a native window wrapper used to intercept and control window messages
''' generated by the Windows Forms color selection interface.
''' </summary>
''' <remarks>
''' This class can prevent the associated native window from being resized by
''' modifying the flags of the <c>WM_WINDOWPOSCHANGING</c> message before it is
''' processed by the operating system.
''' </remarks>
Friend Class ColorUIWnd
    Inherits NativeWindow
    ''' <summary>
    ''' Contains information about the size, position, and Z-order of a native window.
    ''' </summary>
    ''' <remarks>
    ''' This structure represents the Win32 <c>WINDOWPOS</c> structure received
    ''' through the <c>WM_WINDOWPOSCHANGING</c> message.
    ''' </remarks>
    <StructLayout(LayoutKind.Sequential)>
    Private Structure WINDOWPOS
        ''' <summary>
        ''' Identifies the window whose position or size is being changed.
        ''' </summary>
        Public hwnd As IntPtr
        ''' <summary>
        ''' Identifies the window that precedes this window in the Z-order.
        ''' </summary>
        Public hwndInsertAfter As IntPtr
        ''' <summary>
        ''' Specifies the new horizontal position of the window.
        ''' </summary>
        Public x As Integer
        ''' <summary>
        ''' Specifies the new vertical position of the window.
        ''' </summary>
        Public y As Integer
        ''' <summary>
        ''' Specifies the new width of the window.
        ''' </summary>
        Public cx As Integer
        ''' <summary>
        ''' Specifies the new height of the window.
        ''' </summary>
        Public cy As Integer
        ''' <summary>
        ''' Specifies flags that control the window position and size operation.
        ''' </summary>
        Public flags As Integer
    End Structure
    ''' <summary>
    ''' Specifies the Win32 message sent to a window when its size, position,
    ''' or Z-order is about to change.
    ''' </summary>
    Private Const WM_WINDOWPOSCHANGING As Integer = &H46
    ''' <summary>
    ''' Specifies that the current window size must be retained.
    ''' </summary>
    Private Const SWP_NOSIZE As Integer = &H1
    ''' <summary>
    ''' Indicates whether resizing of the associated native window must be prevented.
    ''' </summary>
    ''' <remarks>
    ''' When set to <see langword="True"/>, the <c>SWP_NOSIZE</c> flag is added
    ''' to every intercepted <c>WM_WINDOWPOSCHANGING</c> message. When set to
    ''' <see langword="False"/>, window messages are processed without modification.
    ''' </remarks>
    Public PreventSizing As Boolean
    ''' <summary>
    ''' Processes native Windows messages sent to the associated window.
    ''' </summary>
    ''' <param name="m">
    ''' A <see cref="Message"/> structure containing the native window message
    ''' to process.
    ''' </param>
    ''' <remarks>
    ''' If <see cref="PreventSizing"/> is enabled and the received message is
    ''' <c>WM_WINDOWPOSCHANGING</c>, this method updates its <c>WINDOWPOS</c>
    ''' structure with the <c>SWP_NOSIZE</c> flag before forwarding the message
    ''' to the base implementation.
    ''' </remarks>
    Protected Overrides Sub WndProc(ByRef m As Message)
        If PreventSizing AndAlso m.Msg = WM_WINDOWPOSCHANGING Then
            Dim WindowPosition As WINDOWPOS = CType(Marshal.PtrToStructure(m.LParam, GetType(WINDOWPOS)), WINDOWPOS)
            WindowPosition.flags = WindowPosition.flags Or SWP_NOSIZE
            Marshal.StructureToPtr(WindowPosition, m.LParam, False)
        End If
        MyBase.WndProc(m)
    End Sub
End Class